maanantainlukemat = paivantiedot("13.10.2025", lukemat)
    print(f"Maanantai   13.10.2025", f"{maanantainlukemat[0]:6.2f}".replace('.',','), end="")
    print(f"{maanantainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{maanantainlukemat[2]:6.2f}".replace('.',','), end="\t")
    print(f"{maanantainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{maanantainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{maanantainlukemat[5]:6.2f}".replace('.',','),)
    maanantainlukemat = paivantiedot("13.10.2025", lukemat)
    print("")
    tuntitiedot("13.10.2025", lukemat)

    
    tiistainlukemat = paivantiedot("14.10.2025", lukemat)
    print(f"Tiistai     14.10.2025", f"{tiistainlukemat[0]:6.2f}".replace('.',','), end="" )
    print( f"{tiistainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{tiistainlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{tiistainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{tiistainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{tiistainlukemat[5]:6.2f}".replace('.',','),)
    tiistainlukematlukemat = paivantiedot("13.10.2025", lukemat)
    print("")
    tuntitiedot("14.10.2025", lukemat)

    keskiviikonlukemat = paivantiedot("15.10.2025", lukemat)
    print(f"Keskiviikko 15.10.2025", f"{keskiviikonlukemat[0]:6.2f}".replace('.',','), end= "")
    print( f"{keskiviikonlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{keskiviikonlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{keskiviikonlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{keskiviikonlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{keskiviikonlukemat[5]:6.2f}".replace('.',','),)
    print("")
    tuntitiedot("15.10.2025", lukemat)

    torstainlukemat = paivantiedot("16.10.2025", lukemat)
    print(f"Torstai     16.10.2025", f"{torstainlukemat[0]:6.2f}".replace('.',','), end= "")
    print( f"{torstainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{torstainlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{torstainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{torstainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{torstainlukemat[5]:6.2f}".replace('.',','),)
    print("")
    tuntitiedot("16.10.2025", lukemat)

    perjantainlukemat = paivantiedot("17.10.2025", lukemat)
    print(f"Perjantai   17.10.2025", f"{perjantainlukemat[0]:6.2f}".replace('.',','), end= "")
    print( f"{perjantainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{perjantainlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{perjantainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{perjantainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{perjantainlukemat[5]:6.2f}".replace('.',','),)
    print("")
    tuntitiedot("17.10.2025", lukemat)

    lauantainlukemat = paivantiedot("18.10.2025", lukemat)
    print(f"Lauantai    18.10.2025", f"{lauantainlukemat[0]:6.2f}".replace('.',','), end= "")
    print( f"{lauantainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{lauantainlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{lauantainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{lauantainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{lauantainlukemat[5]:6.2f}".replace('.',','),)
    print("")
    tuntitiedot("18.10.2025", lukemat)
    print(f"---------------------------------------------------------")
    sunnuntainlukemat = paivantiedot("19.10.2025", lukemat)
    print(f"Päivän kokonaismittaus:")
    print(f"Sunnuntai   19.10.2025", f"{sunnuntainlukemat[0]:6.2f}".replace('.',','), end= "")
    print( f"{sunnuntainlukemat[1]:6.2f}".replace('.',','), end= "\t")
    print(f"{sunnuntainlukemat[2]:6.2f}".replace('.',','), end= "\t\t")
    print(f"{sunnuntainlukemat[3]:6.2f}".replace('.',','), end= "\t")
    print(f"{sunnuntainlukemat[4]:6.2f}".replace('.',','), end= "\t")
    print(f"{sunnuntainlukemat[5]:6.2f}".replace('.',','),)
    print("")
    tuntitiedot("19.10.2025", lukemat)